// src/reducers/counterSlice.js

// Importing the createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Creating a slice of the Redux store for managing the counter state
const counterSlice = createSlice({
  // Name of the slice, used to identify it in the Redux store
  name: 'counter',
  // Initial state of the counter slice, which is a number (0 in this case)
  initialState: 0,
  // Reducer functions to handle actions that modify the counter state
  reducers: {
    // Reducer function for incrementing the counter state by 1
    increment: state => state + 1,
    // Reducer function for decrementing the counter state by 1
    decrement: state => state - 1,
  },
});

// Extracting the action creators generated by createSlice for increment and decrement actions
export const { increment, decrement } = counterSlice.actions;
// Exporting the reducer function generated by createSlice
export default counterSlice.reducer;
